### ISSUE TITLE
I don’t even know if you monitor the site anymore, but the server has become completely unresponsive.

### ISSUE THREAD

**Issue by grunge00** [miraclx/talk.chat#1]
It’s impossible to open, and although this app isn’t like, the second coming of Christ, I and a bunch of good friends use it since it’s the only one with no actual signup.

**Comment by miraclx** [comment]
Hi @grunge00, I don't quite understand what the issue is here.

Please include information about what exactly is going wrong.

And if this is a newly developed error, incase it worked just fine before.

Thanks,
Miraculous

**Comment by miraclx** [comment]
Hi, maybe this might suit your interests

https://github.com/lemunozm/termchat

---

This is unmaintained anyways
